### ISSUE TITLE
Unmerging feature is not working

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#408]
The Unmerging for  course section could be done from 2 places. The unmerging is not working when we open the `Merge Section` from landing page and if there are sections that are listed in the right column that are crosslisted into the current course.  

Console log show this error

```
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
    at button
    at ButtonBase (https://8831-141-213-171-192.ngrok-free.app/main-578b7839b959ef2f659a.js:1711:22)
    at WithStyles (https://8831-141-213-171-192.ngrok-free.app/main-578b7839b959ef2f659a.js:23708:31)
    at Button (https://8831-141-213-171-192.ngrok-free.app/main-578b7839b959ef2f659a.js:1469:24)
    at WithStyles (https://8831-141-213-171-192.ngrok-free.app/main-578b7839b959ef2f659a.js:23708:31)
    at p
    at Typography (https://8831-141-213-171-192.ngrok-free.app/main-578b7839b959ef2f659a.js:18489:28)
    at WithStyles (https://8831-141-213-171-192.ngrok-free.app/main-578b7839b959ef2f659a.js:23708:31)
    at div
```

**Comment by ktowneUM** [comment]
Unmerging button works from the landing page (not the page displayed after clicking GO MERGE)
